-- DROP USER BTMS;

CREATE USER BTMS
-- IDENTIFIED BY <password>
;


--DROP TABLE CUSTOMER;
--CUSTOMER
CREATE TABLE CUSTOMER (
customer_id NUMBER PRIMARY KEY,
address VARCHAR2(250),
Phone NUMBER(15),
email VARCHAR2(100),
PAN VARCHAR2(10) NOT NULL,
AADHAR NUMBER(12) NOT NULL,
status VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL
    CHECK (status IN ('ACTIVE', 'BLOCKED')),
created_at DATE,
Last_modified_at DATE
);

ALTER TABLE CUSTOMER ADD FIRST_NAME VARCHAR2(100) NOT NULL;
ALTER TABLE CUSTOMER ADD SURNAME VARCHAR2(100) NOT NULL;
ALTER TABLE CUSTOMER MODIFY created_at DEFAULT SYSDATE;

--ACCOUNT_TYPE
CREATE TABLE ACCOUNT_TYPE (
account_TYPE_CODE VARCHAR2(20) PRIMARY KEY,
account_TYPE_DESC VARCHAR2(200),
created_at DATE,
Last_modified_at DATE
);
ALTER TABLE ACCOUNT_TYPE MODIFY created_at DEFAULT SYSDATE;

--BRANCH
CREATE TABLE BRANCH (
BRANCH_CODE VARCHAR2(20) PRIMARY KEY,
BRANCH_NAME VARCHAR2(200),
created_at DATE DEFAULT SYSDATE,
Last_modified_at DATE
);

--ACCOUNT
CREATE TABLE ACCOUNT (
account_id NUMBER PRIMARY KEY,
BRANCH_CODE VARCHAR2(100),
customer_id NUMBER REFERENCES CUSTOMER(customer_id),
ACCOUNT_TYPE VARCHAR2(25)REFERENCES ACCOUNT_TYPE(account_TYPE_CODE),
balance NUMBER NOT NULL,
status VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL
    CHECK (status IN ('ACTIVE', 'BLOCKED')),
created_at DATE,
Last_modified_at DATE
);
ALTER TABLE ACCOUNT MODIFY created_at DEFAULT SYSDATE;
ALTER TABLE ACCOUNT MODIFY BRANCH_CODE REFERENCES BRANCH(BRANCH_CODE);

--transaction audit
CREATE TABLE TXN_LOG( 
txn_id NUMBER PRIMARY KEY,
txn_timestamp DATE DEFAULT SYSDATE,
from_acct_id NUMBER REFERENCES ACCOUNT(account_id),
to_acct_id NUMBER REFERENCES ACCOUNT(account_id),
txn_type VARCHAR2(10) DEFAULT 'CREATE' NOT NULL
    CHECK (txn_type IN ('CREATE', 'DEPOSIT', 'WITHDRAW', 'TRANSFER')),
amount NUMBER,
status VARCHAR2(10) DEFAULT 'SUCCESS' NOT NULL
    CHECK (status IN ('SUCCESS', 'FAILED')),
error_msg VARCHAR2(1000),
created_at DATE,
Last_modified_at DATE
);
ALTER TABLE TXN_LOG MODIFY created_at DEFAULT SYSDATE;
ALTER TABLE TXN_LOG MODIFY txn_type VARCHAR2(50);
ALTER TABLE TXN_LOG MODIFY txn_type DEFAULT NULL;
ALTER TABLE TXN_LOG DROP CONSTRAINT SYS_C008589;
ALTER TABLE TXN_LOG MODIFY  CHECK(txn_type IN('DEPOSIT','WITHDRAWAL','FUND TRANSFER','INTEREST CREDIT',
'ATM WITHDRAWAL','UPI','NEFT','IMPS','CASH'));
ALTER TABLE TXN_LOG DROP CONSTRAINT SYS_C008581;--Removed foreign key constraint from from account_id



--Sequences: seq_account_id, seq_txn_id to generate keys.
CREATE SEQUENCE seq_account_id
START WITH
1 INCREMENT BY 1;

CREATE SEQUENCE seq_txn_id
START WITH
1 INCREMENT BY 1;

ALTER SEQUENCE seq_txn_id RESTART START WITH 10001;

--Optional index on txn_log.from_acct_id, txn_log.to_acct_id for quick history.
CREATE INDEX idx_from_acct_id
ON
txn_log (from_acct_id);

CREATE INDEX idx_to_acct_id
ON
txn_log (to_acct_id);

